=encoding utf8

=head1 谢谢

该文源自阮一峰的博文，谢谢 !!!
L<http://www.ruanyifeng.com/blog/2012/02/a_history_of_unix_directory_structure.html>

=head1 Unix目录结构的来历

疑惑Unix（Linux）目录结构的含有吗？

=begin html

<p><img src="https://github.com/noodles-v6/myfqa/raw/master/images/directory-structs.jpg" /></p>

=end html

举例来说，根目录下面有一个子目录/bin，用于存放二进制程序。但是，/usr子目录下面还有/usr/bin，以及/usr/local/bin，也用于存放二进制程序；某些系统甚至还有/opt/bin。它们有何区别？

话说1969年，Ken Thompson和Dennis
Ritchie在小型机PDP-7上发明了Unix。1971年，他们将主机升级到了PDP-11。

=begin html

<p><img src="https://github.com/noodles-v6/myfqa/raw/master/images/big-cipan.jpg" /></p>

=end html 

当然，他们使用一种叫做RKo5的储存盘，一盘的容量大约是1.5MB。

=begin html

<p><img src="https://github.com/noodles-v6/myfqa/raw/master/images/RK05.jpg" /></p>

=end html 

没过多久，操作系统（根目录）变得越来越大，一块盘已经装不下了。于是，他们加上了第二盘RKo5，并且规定第一块盘专门放系统程序，第二块盘专门放用户自己的程序，因此挂载的目录取名为/usr。也就是说，根目录"/"挂载在第一块盘，"/usr"目录挂载在第二块盘。除此之外，两块盘的目录结构完全相同，第一块盘的目录（/bin，/sbin，/lib，/tmp
...）都在/usr目录下重新出现了一次。

从此，这种目录结构就延续了下来。随着硬盘容量越来越大，各个目录的含义进一步得到明确。

    /           : 存放系统程序，也就是At&t开发的Unix程序。
    /usr        : 存放Unix系统商（比如IBM和HP）开发的程序。
    /usr/local  : 存放用户自己安装的程序。
    /opt        : 在某些系统，用于存放第三方厂商开发的程序，如Oracle，所以取名为option，意为“选装”。

=head1 更多链接

要是深入了解还是要看看这篇文章L<Unix文件系统结构标准|http://www.pathname.com/fhs/pub/fhs-2.3.html>

也可以Rob Landley的L<简短解释|http://lists.busybox.net/pipermail/busybox/2010-December/074114.html>
